version: "3"

services:
  haproxy:
    build: haproxy
    ports:
      - "8001:8001"
    links:
      - "server"
    environment:
      - SERVER_HOSTNAME=server
      - SERVER_PORT=8000
  mitmproxy:
    build: mitmproxy
    ports:
      - "8002:8002"
    links:
      - "server"
    environment:
      - SERVER_HOSTNAME=server
      - SERVER_PORT=8000
  squidproxy:
    build: squidproxy
    ports:
      - "8003:8003"
    links:
      - "server"
  server:
    build: gunicornserver
